// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NgCinema.Infraestructure.Persistence;

#nullable disable

namespace NgCinema.Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NgCinema.Domain.Entities.Function", b =>
                {
                    b.Property<int>("IdFuntion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuntion"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMovie")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("IdFuntion");

                    b.HasIndex("IdMovie");

                    b.HasIndex("IdRoom");

                    b.ToTable("Funciones", (string)null);
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGenre");

                    b.ToTable("Generos", (string)null);

                    b.HasData(
                        new
                        {
                            IdGenre = 1,
                            Name = "Acción"
                        },
                        new
                        {
                            IdGenre = 2,
                            Name = "Aventuras"
                        },
                        new
                        {
                            IdGenre = 3,
                            Name = "Ciencia Ficción"
                        },
                        new
                        {
                            IdGenre = 4,
                            Name = "Comedia"
                        },
                        new
                        {
                            IdGenre = 5,
                            Name = "Documental"
                        },
                        new
                        {
                            IdGenre = 6,
                            Name = "Drama"
                        },
                        new
                        {
                            IdGenre = 7,
                            Name = "Fantasía"
                        },
                        new
                        {
                            IdGenre = 8,
                            Name = "Musical"
                        },
                        new
                        {
                            IdGenre = 9,
                            Name = "Suspenso"
                        },
                        new
                        {
                            IdGenre = 10,
                            Name = "Terror"
                        });
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("IdMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovie"));

                    b.Property<int>("IdGenre")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("synopsis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdMovie");

                    b.HasIndex("IdGenre");

                    b.ToTable("Peliculas", (string)null);

                    b.HasData(
                        new
                        {
                            IdMovie = 1,
                            IdGenre = 8,
                            Poster = "BohemianRhapsody.png",
                            Title = "Bohemian Rhapsody",
                            Trailer = "BohemianRhapsody.mp4",
                            synopsis = "El joven Farrokh, Freddie, se ofrece como cantante de la banda al enterarse de que se han quedado sin vocalista. Ninguno de ellos se imaginaba por aquel entonces que se convertirían en los mismísimos Queen."
                        },
                        new
                        {
                            IdMovie = 2,
                            IdGenre = 1,
                            Poster = "HarryPotter.png",
                            Title = "Harry Potter y El misterio del príncipe",
                            Trailer = "TrailerHarryPotter.mp4",
                            synopsis = "Sexta entrega de la saga del joven mago, en la que Harry descubre un poderoso libro y, mientras trata de descubrir sus orígenes, colabora con Dumbledore en la búsqueda de una serie de objetos mágicos que ayudarán en la destrucción de Lord Voldemort."
                        },
                        new
                        {
                            IdMovie = 3,
                            IdGenre = 7,
                            Poster = "Cars.png",
                            Title = "Cars",
                            Trailer = "Cars.mp4",
                            synopsis = "El aspirante a campeón de carreras Rayo McQueen parece que está a punto de conseguir el éxito. Su actitud arrogante se desvanece cuando llega a una pequeña comunidad olvidada que le enseña las cosas importantes de la vida que había olvidado."
                        },
                        new
                        {
                            IdMovie = 4,
                            IdGenre = 1,
                            Poster = "Rocky2.png",
                            Title = "Rocky 2",
                            Trailer = "Rocky.mp4",
                            synopsis = "Rocky ha colgado los guantes de boxeo. Sin embargo, acepta la oferta de revancha de Apollo para una segunda pelea. Reticente, acepta cuando éste le llama cobarde, se teme que la pelea pueda acabar con el ya retirado Rocky."
                        },
                        new
                        {
                            IdMovie = 5,
                            IdGenre = 7,
                            Poster = "ToyStory3.png",
                            Title = "Toy Story 3",
                            Trailer = "ToyStory3.mp4",
                            synopsis = "Cuando su dueño Andy comienza la universidad Woody, Buzz y el resto de sus amigos juguetes comienzan a preocuparse por su incierto futuro. Todos acaban en una guardería donde comenzarán una serie de trepidantes y divertidas aventuras."
                        },
                        new
                        {
                            IdMovie = 6,
                            IdGenre = 5,
                            Poster = "Oppenheimer.png",
                            Title = "Oppenheimer",
                            Trailer = "Oppenheimer.mp4",
                            synopsis = "El físico J Robert Oppenheimer trabaja con un equipo de científicos durante el Proyecto Manhattan, que condujo al desarrollo de la bomba atómica."
                        },
                        new
                        {
                            IdMovie = 7,
                            IdGenre = 3,
                            Poster = "Interstellar.png",
                            Title = "Interstellar",
                            Trailer = "Interstellar.mp4",
                            synopsis = "Un grupo de científicos y exploradores, encabezados por Cooper, realizan un viaje espacial para encontrar un lugar con las condiciones necesarias para reemplazar a la Tierra.Este grupo necesita encontrar un planeta más que garantice el futuro humano"
                        },
                        new
                        {
                            IdMovie = 8,
                            IdGenre = 10,
                            Poster = "IT.png",
                            Title = "IT",
                            Trailer = "IT.mp4",
                            synopsis = "Varios niños de una pequeña ciudad del estado de Maine se alían para combatir a una entidad diabólica que adopta la forma de un payaso y desde hace mucho tiempo emerge cada 27 años para saciarse de sangre infantil."
                        },
                        new
                        {
                            IdMovie = 9,
                            IdGenre = 1,
                            Poster = "spiderman.png",
                            Title = "Spiderman 1",
                            Trailer = "spiderman.mp4",
                            synopsis = "Al sufrir la picadura de una araña genéticamente modificada, un estudiante de secundaria tímido y torpe adquiere increíbles capacidades como arácnido. Pronto comprenderá que su misión es utilizarlas para luchar contra el mal y defender a sus vecinos."
                        },
                        new
                        {
                            IdMovie = 10,
                            IdGenre = 6,
                            Poster = "RedSocial.png",
                            Title = "Red social",
                            Trailer = "RedSocial.mp4",
                            synopsis = "La historia de los jóvenes fundadores de la popular red social Facebook, especialmente de su creador más conocido, Mark Zuckerberg. Su leyenda reza: 'No se hacen 500 millones de amigos sin hacer unos cuantos enemigos'."
                        },
                        new
                        {
                            IdMovie = 11,
                            IdGenre = 4,
                            Poster = "BuenosVecinos.png",
                            Title = "Buenos Vecinos",
                            Trailer = "BuenosVecinos.mp4",
                            synopsis = "Mac y Kelly acaban de tener una niña adorable y se han comprado una preciosa casa en las afueras. Pero estos exjuerguistas descubren de pronto que sus nuevos vecinos son los miembros de la fraternidad Delta Psi Beta, con el presidente Teddy Sanders."
                        },
                        new
                        {
                            IdMovie = 12,
                            IdGenre = 1,
                            Poster = "Batman.png",
                            Title = "Batman: el caballero de la noche",
                            Trailer = "Batman.mp4",
                            synopsis = "Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman mantiene a raya el crimen organizado en Gotham. Todo cambia cuando aparece el Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos."
                        },
                        new
                        {
                            IdMovie = 13,
                            IdGenre = 9,
                            Poster = "IslaSiniestra.png",
                            Title = "La isla siniestra",
                            Trailer = "IslaSiniestra.mp4",
                            synopsis = "Los agentes son enviados a una isla del puerto de Boston para investigar la desaparición de una asesina en el hospital psiquiátrico, un centro penitenciario para criminales. El centro guarda secretos y la isla esconde algo más peligroso que los pacientes."
                        },
                        new
                        {
                            IdMovie = 14,
                            IdGenre = 6,
                            Poster = "SecretoDeSusOjos.png",
                            Title = "El secreto de sus ojos",
                            Trailer = "SecretoDeSusOjos.mp4",
                            synopsis = "Benjamín Espósito es un oficial de un Juzgado de Instrucción jubilado. Su sueño es escribir una novela. intentará dar solución a un caso viejo, del cual fue testigo y protagonista. "
                        },
                        new
                        {
                            IdMovie = 15,
                            IdGenre = 5,
                            Poster = "soldadoRyan.png",
                            Title = "Rescatando al soldado Ryan",
                            Trailer = "soldadoRyan.mp4",
                            synopsis = "Después de desembarcar en Normandía, en plena Segunda Guerra Mundial, unos soldados norteamericanos deben arriesgar sus vidas para salvar al soldado James Ryan, cuyos tres hermanos han muerto en la guerra."
                        },
                        new
                        {
                            IdMovie = 16,
                            IdGenre = 7,
                            Poster = "sherk.png",
                            Title = "Sherk 2",
                            Trailer = "sherk.mp4",
                            synopsis = "Shrek, nuestro ogro favorito, debe enfrentarse al mayor de los problemas que se podía imaginar: conocer a sus suegros."
                        },
                        new
                        {
                            IdMovie = 17,
                            IdGenre = 3,
                            Poster = " StarWars.png",
                            Title = "Star Wars: Episodio IV",
                            Trailer = " StarWars.mp4",
                            synopsis = "Princesa Leia es capturada por el temible DarthVader. Leia consigue introducir un mensaje en su robot. Tras aterrizar son capturados y vendidos al joven Luke Skywalker, quien descubrirá el mensaje oculto que va destinado a Obi Wan Kenobi, maestro Jedi."
                        },
                        new
                        {
                            IdMovie = 18,
                            IdGenre = 2,
                            Poster = "ForrestGump.png",
                            Title = "Forrest Gump",
                            Trailer = "ForrestGump.mp4",
                            synopsis = "Forrest Gump espera al autobús. Mientras éste tarda en llegar, el joven cuenta su vida . Aunque sufre un pequeño retraso mental, esto no le impide hacer cosas maravillosas. el toma partido en los eventos más importantes de la historia de los EEUU."
                        },
                        new
                        {
                            IdMovie = 19,
                            IdGenre = 5,
                            Poster = "ElLoboWallStreet.png",
                            Title = "El lobo de Wall Street",
                            Trailer = "WallStreet.mp4",
                            synopsis = "La historia del corredor de bolsa neoyorquino Jordan Belfort, quien, con poco más de veinte años, fue apodado 'el lobo de Wall Street' por su enorme éxito y fortuna como fundador de la agencia bursátil Stratton Oakmont."
                        },
                        new
                        {
                            IdMovie = 20,
                            IdGenre = 1,
                            Poster = "ElClubDeLaPelea.png",
                            Title = "El club de la pelea",
                            Trailer = "ElClubDeLaPelea.mp4",
                            synopsis = "Un empleado de oficina insomne, harto de su vida, se cruza con un vendedor peculiar. Ambos crean un club de lucha clandestino como forma de terapia y, poco a poco, la organización crece y sus objetivos toman otro rumbo."
                        });
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoom"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRoom");

                    b.ToTable("Salas", (string)null);

                    b.HasData(
                        new
                        {
                            IdRoom = 1,
                            Capacity = 5,
                            Name = "Sala 1"
                        },
                        new
                        {
                            IdRoom = 2,
                            Capacity = 15,
                            Name = "Sala 2"
                        },
                        new
                        {
                            IdRoom = 3,
                            Capacity = 35,
                            Name = "Sala 3"
                        });
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicket"));

                    b.Property<int>("IdFunction")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTicket");

                    b.HasIndex("IdFunction");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Function", b =>
                {
                    b.HasOne("NgCinema.Domain.Entities.Movie", "Movie")
                        .WithMany("Functions")
                        .HasForeignKey("IdMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NgCinema.Domain.Entities.Room", "Room")
                        .WithMany("Functions")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Movie", b =>
                {
                    b.HasOne("NgCinema.Domain.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("IdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("NgCinema.Domain.Entities.Function", "Function")
                        .WithMany("Tickets")
                        .HasForeignKey("IdFunction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Function", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Movie", b =>
                {
                    b.Navigation("Functions");
                });

            modelBuilder.Entity("NgCinema.Domain.Entities.Room", b =>
                {
                    b.Navigation("Functions");
                });
#pragma warning restore 612, 618
        }
    }
}
